/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Red Fox / nokillnando (https://sketchfab.com/nokillnando)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/laptop-f34c1400926e430a9ef10bb180986b42
title: Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lapi.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.35, 0.13,-0.3]} rotation={[-Math.PI / 2, 0, 0]} scale={10}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.LaptopKeys} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={10}>
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.LapTopMisc} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={10}>
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.LaptopKeys} />
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.LaptopBack} />
            <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.LaptopFront} />
          </group>
          <group position={[0, 0.11, -1.2]} rotation={[-Math.PI / 2, 0, 0]} scale={10}>
            <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.LaptopScreen} />
            <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.LaptopBack} />
            <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.LaptopFront} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lapi.gltf')
